USE [FINDB]
GO

/****** Object:  Table [dbo].[WFPEXTRA]    Script Date: 2026/4/15 下午 08:45:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WFPEXTRA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[APLNO] [char](10) NOT NULL,
	[ITEMNUM] [decimal](4, 0) NOT NULL,
	[EXPID] [varchar](10) NOT NULL,
	[EFORMSN] [int] NULL,
	[TAXTYP] [varchar](10) NULL,
	[TAXAMOUNT] [decimal](10, 2) NULL,
	[THEDATE] [int] NULL,
	[COMPANYLOCATION] [nvarchar](60) NULL,
	[COMPANYPEOPLE] [nvarchar](60) NULL,
	[MODIFIEDDATETIME] [datetime] NULL,
 CONSTRAINT [PK_WFPEXTRA_ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[WFPEXTRA] ADD  DEFAULT (getdate()) FOR [MODIFIEDDATETIME]
GO

