USE [FINDB]
GO

/****** Object:  Table [dbo].[WFPINVOICE]    Script Date: 2026/4/15 下午 08:44:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WFPINVOICE](
	[IDGNO] [int] IDENTITY(1,1) NOT NULL,
	[APLNO] [varchar](10) NOT NULL,
	[EFORMSN] [int] NULL,
	[FILEONAME] [nvarchar](100) NOT NULL,
	[FILEO] [nvarchar](100) NOT NULL,
	[EMPNO] [char](5) NOT NULL,
	[MODIFIEDDATETIME] [datetime] NULL,
 CONSTRAINT [PK_IDGNO] PRIMARY KEY CLUSTERED 
(
	[IDGNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[WFPINVOICE] ADD  DEFAULT (getdate()) FOR [MODIFIEDDATETIME]
GO

