USE [FINDB]
GO

/****** Object:  Table [dbo].[WFPPAYEZ]    Script Date: 2026/4/15 下午 08:47:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WFPPAYEZ](
	[YY] [int] NOT NULL,
	[MM] [int] NOT NULL,
	[COUNTER] [int] NOT NULL,
	[MAXTRIPNO] [int] NULL,
 CONSTRAINT [PK_WFPPAYZ] PRIMARY KEY CLUSTERED 
(
	[YY] ASC,
	[MM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 30) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[WFPPAYEZ] ADD  CONSTRAINT [DF_WFPPAYEZ_MAXTRIPNO]  DEFAULT (0) FOR [MAXTRIPNO]
GO

