USE [FINDB]
GO

/****** Object:  Table [dbo].[WFPPAYEH]    Script Date: 2026/4/15 下午 08:46:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WFPPAYEH](
	[APLNO] [char](10) NOT NULL,
	[APLSEQ] [decimal](3, 0) NOT NULL,
	[EXPID] [char](10) NOT NULL,
	[ITEMDES] [nvarchar](22) NOT NULL,
	[SHAREC] [char](4) NOT NULL,
	[APLAMT] [decimal](11, 0) NOT NULL,
	[CATGCD1] [varchar](4) NULL,
 CONSTRAINT [PK_WFPPAYEH] PRIMARY KEY CLUSTERED 
(
	[APLNO] DESC,
	[APLSEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

