USE [FINDB]
GO

/****** Object:  Table [dbo].[WFPPAYEA]    Script Date: 2026/4/15 下午 08:46:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WFPPAYEA](
	[APLNO] [char](10) NOT NULL,
	[ACPTER] [char](10) NOT NULL,
	[ACPTERNAME] [nvarchar](20) NULL,
	[APLAMT] [decimal](14, 2) NULL,
	[PAYTOBNK] [nvarchar](10) NULL,
	[PAYTOACT] [varchar](16) NULL,
	[ACPTERFULLNAME] [varchar](80) NULL,
 CONSTRAINT [PK_WFPPAYEA] PRIMARY KEY CLUSTERED 
(
	[APLNO] DESC,
	[ACPTER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

